const slides=[
{brand:"HASHCODE",kicker:"SESSION 01",background:"./assets/images/opening-cover.webp",time:"00:00",objective:"Créer une ouverture forte.",script:"Laisse deux ou trois secondes de silence. Puis : « Aujourd'hui, je ne suis pas venu vous faire une présentation classique sur l'intelligence artificielle. »",interaction:"Regarde la salle. Ne te précipite pas.",transition:"→ LE TRAVAIL CHANGE"},
{headline:"LE TRAVAIL <span class='accent'>CHANGE.</span>",subheadline:"De l'utilisateur d'IA…<br>…à l'architecte d'un système intelligent.",time:"01:00",objective:"Révéler immédiatement le thème et l'angle de la session.",script:"« Voilà le sujet de cette session. Pas simplement apprendre à utiliser une IA. Comprendre comment notre rôle évolue quand nous travaillons avec des systèmes intelligents. »",interaction:"Laisser le thème s'afficher avant de continuer.",transition:"→ CE SOIR"},
{headline:"CE SOIR,",subheadline:"NOUS ALLONS PARLER<br>DE VOTRE TRAVAIL.",time:"03:00",objective:"Rendre le thème personnel.",script:"« Pas uniquement de ChatGPT. Pas uniquement des prompts. Nous allons parler de ce que cette transformation change pour vous. »",interaction:"Aucune réponse demandée.",transition:"→ UNE QUESTION"},
{headline:"UNE QUESTION.",time:"04:00",objective:"Créer de l'attente.",script:"Ne parle pas immédiatement.",interaction:"Silence de quelques secondes.",transition:"→ COMBIEN DE PERSONNES"},
{headline:"COMBIEN DE PERSONNES<br>TRAVAILLENT AVEC VOUS ?",time:"05:00",objective:"Faire émerger la vision traditionnelle de l'équipe.",script:"« Quand je vous pose cette question, à quoi pensez-vous ? »",interaction:"Prendre 3 à 5 réponses.",transition:"→ VRAIMENT ?"},
{headline:"VRAIMENT ?",subheadline:"Prenez quelques secondes.",time:"07:00",objective:"Installer le doute.",script:"« Je pense que votre réponse aurait probablement été différente il y a seulement quelques années. »",interaction:"Laisser la salle réfléchir.",transition:"→ AVEC QUELLES INTELLIGENCES"},
{headline:"AVEC QUELLES<br><span class='accent'>INTELLIGENCES</span><br>TRAVAILLEZ-VOUS ?",time:"08:00",objective:"Introduire l'idée de collaboration avec des intelligences non humaines.",script:"« Certaines personnes travaillent déjà avec des systèmes capables de rechercher, analyser, écrire, coder et parfois exécuter certaines tâches. »",interaction:"Demander quels outils les participants utilisent réellement.",transition:"→ PARTICIPER"},
{headline:"VOUS N'ÊTES PAS ICI<br>POUR REGARDER.",subheadline:"VOUS ÊTES ICI POUR <span class='accent'>PARTICIPER.</span>",time:"11:00",objective:"Établir le contrat avec le public.",script:"« Cette session ne fonctionnera pas si vous restez simplement assis à écouter. Je vais vous poser des questions. Vous allez réfléchir, répondre et construire. »",interaction:"Obtenir un accord verbal ou gestuel.",transition:"→ LE BASCULEMENT"},
{headline:"LE BASCULEMENT<br>A DÉJÀ COMMENCÉ.",subheadline:"Mais il est facile de ne pas le voir.",time:"13:00",objective:"Entrer dans la Partie II.",script:"« Le changement dont nous parlons n'est pas une prédiction lointaine. Il est déjà en cours. »",interaction:"Questionner la salle sur les changements observés.",transition:"→ AVANT / MAINTENANT"},
{headline:"AVANT,",subheadline:"Nous utilisions des logiciels.<br>Nous cherchions l'information.<br>Nous exécut ions les tâches.",time:"15:00",objective:"Créer le contraste avec l'ancien modèle de travail.",script:"« Le modèle classique était simple : l'humain utilisait des outils. »",interaction:"Faire reconnaître ce modèle au public.",transition:"→ MAINTENANT"},
{headline:"MAINTENANT,",subheadline:"Nous pouvons déléguer une partie du raisonnement.<br>Nous pouvons faire collaborer plusieurs systèmes.<br>Nous pouvons orchestrer des agents.",time:"17:00",objective:"Montrer le changement de nature.",script:"« La différence fondamentale est là : nous ne demandons plus seulement à un outil d'exécuter. Nous pouvons organiser des systèmes capables de contribuer au travail. »",interaction:"Demander un exemple concret aux participants.",transition:"→ CE QUI CHANGE"},
{headline:"LE VRAI CHANGEMENT",subheadline:"Ce n'est pas seulement <span class='accent'>l'outil.</span>",time:"20:00",objective:"Éviter le piège du discours centré sur les outils.",script:"« Chaque semaine, nous parlons d'un nouvel outil. Mais l'outil n'est pas le cœur de la transformation. »",interaction:"Pause.",transition:"→ NOTRE RÔLE"},
{headline:"LE VRAI CHANGEMENT,",subheadline:"C'est notre <span class='accent'>RÔLE.</span>",time:"21:00",objective:"Introduire la thèse centrale.",script:"« Quand une machine peut contribuer à produire, analyser et exécuter, la valeur de l'humain se déplace. »",interaction:"Demander : « Vers quoi, selon vous ? »",transition:"→ QUI PILOTE ?"},
{headline:"SI L'IA PEUT FAIRE UNE PARTIE DU TRAVAIL,",subheadline:"Qui définit le problème ?",time:"23:00",objective:"Déplacer la réflexion vers la formulation des problèmes.",script:"« Une réponse brillante à une mauvaise question reste une mauvaise décision. »",interaction:"Laisser une réponse émerger.",transition:"→ QUI ORCHESTRE ?"},
{headline:"QUI ORCHESTRE<br>LE SYSTÈME ?",time:"25:00",objective:"Introduire le concept d'orchestration.",script:"« Plusieurs intelligences peuvent contribuer. Mais quelqu'un doit décider du but, des règles et des priorités. »",interaction:"Faire le lien avec les métiers du public.",transition:"→ L'ARCHITECTE"},
{headline:"L'UTILISATEUR<br>DEVIENT <span class='accent'>ARCHITECTE.</span>",time:"27:00",objective:"Faire passer le message central de la première grande partie.",script:"« L'enjeu n'est plus uniquement de savoir utiliser l'IA. L'enjeu est de concevoir comment humains et intelligences travaillent ensemble. »",interaction:"Pause longue.",transition:"→ ET VOUS ?"},
{headline:"ET VOUS,",subheadline:"Quel rôle voulez-vous jouer ?",time:"29:00",objective:"Transformer la réflexion en question personnelle.",script:"« Spectateur ? Utilisateur ? Ou architecte de nouveaux systèmes de travail ? »",interaction:"Demander une réponse intérieure, pas forcément publique.",transition:"→ PARTIE III"}
]];
let currentSlide=0,startTime=Date.now();
const presentation=document.getElementById("presentation"),progressBar=document.getElementById("progress-bar");
document.body.insertAdjacentHTML("beforeend",`<aside class="presenter-panel"><div class="presenter-top"><span class="presenter-label">HASHCODE</span><span class="presenter-private">PRIVÉ</span></div><h2>Vue présentateur</h2><div class="timer" id="timer">00:00</div><h3 id="slide-title"></h3><p><strong>Objectif</strong><br><span id="objective"></span></p><p><strong>Script</strong><br><span id="script"></span></p><p><strong>Interaction</strong><br><span id="interaction"></span></p><p><strong>Transition</strong><br><span id="transition"></span></p><div class="presenter-actions"><button class="presenter-prev">← Précédente</button><button class="presenter-next">Suivante →</button></div><p class="presenter-shortcuts">← → navigation · R chronomètre · fermer cette fenêtre pour revenir au mode public</p></aside>`);
function renderSlides(){const s=slides[currentSlide];presentation.innerHTML=slides.map((slide,index)=>`<section class="slide ${slide.background?"has-background":""} ${index===currentSlide?"active":""}" style="${slide.background?`--slide-bg:url(${slide.background})`:""}">${slide.brand?`<div class="brand">${slide.brand}</div>`:""}${slide.kicker?`<div class="kicker">${slide.kicker}</div>`:""}${slide.headline?`<h1 class="headline">${slide.headline}</h1>`:""}${slide.subheadline?`<div class="subheadline">${slide.subheadline}</div>`:""}</section>`).join("");progressBar.style.width=`${((currentSlide+1)/slides.length)*100}%`;document.getElementById("slide-title").textContent=`SLIDE ${currentSlide+1}/${slides.length} · cible ${s.time}`;document.getElementById("objective").textContent=s.objective;document.getElementById("script").textContent=s.script;document.getElementById("interaction").textContent=s.interaction;document.getElementById("transition").textContent=s.transition}
function nextSlide(){if(currentSlide<slides.length-1){currentSlide++;renderSlides()}}function previousSlide(){if(currentSlide>0){currentSlide--;renderSlides()}}
function openPresenter(){const url=new URL(window.location.href);url.searchParams.set("presenter","1");const w=window.open(url.toString(),"hashcode-presenter","popup=yes,width=900,height=900");if(!w){alert("Autorise les fenêtres contextuelles pour ouvrir la vue présentateur.")}}
const isPresenter=new URLSearchParams(window.location.search).get("presenter")==="1";
if(isPresenter){
document.body.classList.add("presenter-window");
document.getElementById("presentation").style.display="none";
document.getElementById("progress").style.display="none";
document.getElementById("controls-hint").textContent="Vue privée · synchronisée avec la présentation";
document.body.classList.add("presenter-mode");
}
function presenterNavigate(delta){
if(!isPresenter)return;
currentSlide=Math.max(0,Math.min(slides.length-1,currentSlide+delta));
renderSlides();
broadcast();
}
document.addEventListener("click",e=>{
if(!isPresenter)return;
const panel=document.querySelector(".presenter-panel");
if(e.target.closest(".presenter-next"))presenterNavigate(1);
if(e.target.closest(".presenter-prev"))presenterNavigate(-1);
});

function broadcast(){localStorage.setItem("hashcode-session-01-slide",JSON.stringify({index:currentSlide,ts:Date.now()}))}
function syncFromStorage(){const raw=localStorage.getItem("hashcode-session-01-slide");if(!raw)return;const data=JSON.parse(raw);if(data.index!==currentSlide){currentSlide=data.index;renderSlides()}}
window.addEventListener("storage",e=>{if(e.key==="hashcode-session-01-slide"&&isPresenter)syncFromStorage()});
const originalRender=renderSlides;renderSlides=function(){originalRender();if(!isPresenter)broadcast()};
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight"||e.key===" "){e.preventDefault();isPresenter?presenterNavigate(1):nextSlide()}if(e.key==="ArrowLeft"){isPresenter?presenterNavigate(-1):previousSlide()}if(e.key.toLowerCase()==="p"&&!isPresenter){openPresenter()}if(e.key.toLowerCase()==="f"&&!isPresenter){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}if(e.key.toLowerCase()==="r"){startTime=Date.now()}});
renderSlides();