const slides=[
{brand:"HASHCODE",kicker:"SESSION 01",background:"./assets/images/opening-cover.webp",time:"00:00",objective:"Créer une ouverture forte.",script:"Laisse deux ou trois secondes de silence. Puis : « Aujourd'hui, je ne suis pas venu vous faire une présentation classique sur l'intelligence artificielle. »",interaction:"Regarde la salle. Ne te précipite pas.",transition:"→ LE TRAVAIL CHANGE"},
{headline:"LE TRAVAIL <span class='accent'>CHANGE.</span>",subheadline:"De l'utilisateur d'IA…<br>…à l'architecte d'un système intelligent.",time:"01:00",objective:"Révéler immédiatement le thème et l'angle de la session.",script:"« Voilà le sujet de cette session. Pas simplement apprendre à utiliser une IA. Comprendre comment notre rôle évolue quand nous travaillons avec des systèmes intelligents. »",interaction:"Laisser le thème s'afficher avant de continuer.",transition:"→ CE SOIR"},
{headline:"CE SOIR,",subheadline:"NOUS ALLONS PARLER<br>DE VOTRE TRAVAIL.",time:"03:00",objective:"Rendre le thème personnel.",script:"« Pas uniquement de ChatGPT. Pas uniquement des prompts. Nous allons parler de ce que cette transformation change pour vous. »",interaction:"Aucune réponse demandée.",transition:"→ UNE QUESTION"},
{headline:"UNE QUESTION.",time:"04:00",objective:"Créer de l'attente.",script:"Ne parle pas immédiatement.",interaction:"Silence de quelques secondes.",transition:"→ COMBIEN DE PERSONNES"},
{headline:"COMBIEN DE PERSONNES<br>TRAVAILLENT AVEC VOUS ?",time:"05:00",objective:"Faire émerger la vision traditionnelle de l'équipe.",script:"« Quand je vous pose cette question, à quoi pensez-vous ? »",interaction:"Prendre 3 à 5 réponses.",transition:"→ VRAIMENT ?"},
{headline:"VRAIMENT ?",subheadline:"Prenez quelques secondes.",time:"07:00",objective:"Installer le doute.",script:"« Je pense que votre réponse aurait probablement été différente il y a seulement quelques années. »",interaction:"Laisser la salle réfléchir.",transition:"→ AVEC QUELLES INTELLIGENCES"},
{headline:"AVEC QUELLES<br><span class='accent'>INTELLIGENCES</span><br>TRAVAILLEZ-VOUS ?",time:"08:00",objective:"Introduire l'idée de collaboration avec des intelligences non humaines.",script:"« Certaines personnes travaillent déjà avec des systèmes capables de rechercher, analyser, écrire, coder et parfois exécuter certaines tâches. »",interaction:"Demander quels outils les participants utilisent réellement.",transition:"→ PARTICIPER"},
{headline:"VOUS N'ÊTES PAS ICI<br>POUR REGARDER.",subheadline:"VOUS ÊTES ICI POUR <span class='accent'>PARTICIPER.</span>",time:"11:00",objective:"Établir le contrat avec le public.",script:"« Cette session ne fonctionnera pas si vous restez simplement assis à écouter. Je vais vous poser des questions. Vous allez réfléchir, répondre et construire. »",interaction:"Obtenir un accord verbal ou gestuel.",transition:"→ LE BASCULEMENT"},
{headline:"LE BASCULEMENT<br>A DÉJÀ COMMENCÉ.",subheadline:"Mais il est facile de ne pas le voir.",time:"13:00",objective:"Entrer dans la Partie II.",script:"« Le changement dont nous parlons n'est pas une prédiction lointaine. Il est déjà en cours. »",interaction:"Questionner la salle sur les changements observés.",transition:"→ AVANT / MAINTENANT"},
{headline:"AVANT,",subheadline:"Nous utilisions des logiciels.<br>Nous cherchions l'information.<br>Nous exécut ions les tâches.",time:"15:00",objective:"Créer le contraste avec l'ancien modèle de travail.",script:"« Le modèle classique était simple : l'humain utilisait des outils. »",interaction:"Faire reconnaître ce modèle au public.",transition:"→ MAINTENANT"},
{headline:"MAINTENANT,",subheadline:"Nous pouvons déléguer une partie du raisonnement.<br>Nous pouvons faire collaborer plusieurs systèmes.<br>Nous pouvons orchestrer des agents.",time:"17:00",objective:"Montrer le changement de nature.",script:"« La différence fondamentale est là : nous ne demandons plus seulement à un outil d'exécuter. Nous pouvons organiser des systèmes capables de contribuer au travail. »",interaction:"Demander un exemple concret aux participants.",transition:"→ CE QUI CHANGE"},
{headline:"LE VRAI CHANGEMENT",subheadline:"Ce n'est pas seulement <span class='accent'>l'outil.</span>",time:"20:00",objective:"Éviter le piège du discours centré sur les outils.",script:"« Chaque semaine, nous parlons d'un nouvel outil. Mais l'outil n'est pas le cœur de la transformation. »",interaction:"Pause.",transition:"→ NOTRE RÔLE"},
{headline:"LE VRAI CHANGEMENT,",subheadline:"C'est notre <span class='accent'>RÔLE.</span>",time:"21:00",objective:"Introduire la thèse centrale.",script:"« Quand une machine peut contribuer à produire, analyser et exécuter, la valeur de l'humain se déplace. »",interaction:"Demander : « Vers quoi, selon vous ? »",transition:"→ QUI PILOTE ?"},
{headline:"SI L'IA PEUT FAIRE UNE PARTIE DU TRAVAIL,",subheadline:"Qui définit le problème ?",time:"23:00",objective:"Déplacer la réflexion vers la formulation des problèmes.",script:"« Une réponse brillante à une mauvaise question reste une mauvaise décision. »",interaction:"Laisser une réponse émerger.",transition:"→ QUI ORCHESTRE ?"},
{headline:"QUI ORCHESTRE<br>LE SYSTÈME ?",time:"25:00",objective:"Introduire le concept d'orchestration.",script:"« Plusieurs intelligences peuvent contribuer. Mais quelqu'un doit décider du but, des règles et des priorités. »",interaction:"Faire le lien avec les métiers du public.",transition:"→ L'ARCHITECTE"},
{headline:"L'UTILISATEUR<br>DEVIENT <span class='accent'>ARCHITECTE.</span>",time:"27:00",objective:"Faire passer le message central de la première grande partie.",script:"« L'enjeu n'est plus uniquement de savoir utiliser l'IA. L'enjeu est de concevoir comment humains et intelligences travaillent ensemble. »",interaction:"Pause longue.",transition:"→ ET VOUS ?"},
{headline:"ET VOUS,",subheadline:"Quel rôle voulez-vous jouer ?",time:"29:00",objective:"Transformer la réflexion en question personnelle.",script:"« Spectateur ? Utilisateur ? Ou architecte de nouveaux systèmes de travail ? »",interaction:"Demander une réponse intérieure, pas forcément publique.",transition:"→ PARTIE III"},
{headline:"PARTIE III",subheadline:"UNE JOURNÉE DE TRAVAIL<br>QUI NE RESSEMBLE PLUS À AVANT.",time:"31:00",objective:"Faire basculer la présentation de l'abstrait vers le concret.",script:"« Jusqu'ici, nous avons parlé d'une transformation. Maintenant, je veux vous la faire vivre. »",interaction:"Annoncer une immersion concrète.",transition:"→ 08:00"},
{headline:"08:00",subheadline:"UNE NOUVELLE JOURNÉE COMMENCE.",time:"32:00",objective:"Installer un scénario réaliste.",script:"« Imaginez votre prochaine journée de travail. »",interaction:"Demander au public de visualiser son propre bureau.",transition:"→ LE PROBLÈME"},
{headline:"08:07",subheadline:"UN PROBLÈME APPARAÎT.",time:"33:00",objective:"Créer une situation familière.",script:"« Un client attend une réponse. Une décision doit être prise. Des informations sont dispersées. Le temps est limité. »",interaction:"Demander qui reconnaît cette situation.",transition:"→ AVANT"},
{headline:"AVANT,",subheadline:"Vous commenciez à chercher.",time:"34:00",objective:"Rappeler l'ancien réflexe.",script:"« Onglet après onglet. Recherche après recherche. Copier. Comparer. Organiser. »",interaction:"Laisser les participants reconnaître leurs habitudes.",transition:"→ MAINTENANT"},
{headline:"MAINTENANT,",subheadline:"VOUS COMMENCEZ PAR<br><span class='accent'>DÉFINIR LE SYSTÈME.</span>",time:"35:00",objective:"Montrer le changement de point de départ.",script:"« La première question n'est plus : quel outil vais-je utiliser ? La première question devient : quel système peut m'aider à résoudre ce problème ? »",interaction:"Insister sur la différence.",transition:"→ AGENT 01"},
{headline:"AGENT 01",subheadline:"RECHERCHE.<br>COLLECTE.<br>SYNTHÉTISE.",time:"36:00",objective:"Illustrer une première délégation.",script:"« Vous déléguez l'exploration initiale. Mais vous définissez le périmètre et les critères. »",interaction:"Question : « Que ne délégueriez-vous jamais aveuglément ? »",transition:"→ AGENT 02"},
{headline:"AGENT 02",subheadline:"ANALYSE.<br>COMPARE.<br>IDENTIFIE LES OPTIONS.",time:"38:00",objective:"Montrer la complémentarité des rôles.",script:"« Un autre système peut examiner les informations selon une autre logique. »",interaction:"Faire remarquer qu'avoir plusieurs sorties ne signifie pas avoir plusieurs décisions.",transition:"→ VOUS"},
{headline:"ET VOUS ?",subheadline:"VOUS NE DISPARAISSEZ PAS.<br>VOTRE RÔLE <span class='accent'>MONTE.</span>",time:"40:00",objective:"Dissiper l'idée du remplacement.",script:"« Vous définissez le problème. Vous arbitrez. Vous vérifiez. Vous assumez la décision. »",interaction:"Pause.",transition:"→ 10:30"},
{headline:"10:30",subheadline:"LE TRAVAIL A AVANCÉ.<br>MAIS QUI EST RESPONSABLE ?",time:"42:00",objective:"Introduire la responsabilité humaine.",script:"« Plus un système devient autonome, plus la question de la responsabilité devient importante. »",interaction:"Demander : « Qui signe la décision finale ? »",transition:"→ L'HUMAIN"},
{headline:"L'HUMAIN NE QUITTE PAS LE SYSTÈME.",subheadline:"IL EN DEVIENT LE <span class='accent'>CONCEPTEUR.</span>",time:"44:00",objective:"Ancrer la thèse centrale avec le scénario.",script:"« Voilà le basculement. L'humain n'est plus seulement devant un outil. Il organise un environnement de travail intelligent. »",interaction:"Silence et regard vers la salle.",transition:"→ LE TEST"},
{headline:"LE TEST",subheadline:"SI L'IA S'ARRÊTAIT DEMAIN…<br>QUE RESTERAIT-IL DE VOTRE VALEUR ?",time:"46:00",objective:"Créer une réflexion personnelle forte.",script:"« Votre valeur ne peut pas reposer uniquement sur votre capacité à cliquer plus vite qu'une machine. »",interaction:"30 secondes de réflexion individuelle.",transition:"→ CE QUI RESTE"},
{headline:"CE QUI RESTE",subheadline:"LE JUGEMENT.<br>LE CONTEXTE.<br>LA RESPONSABILITÉ.<br>LA VISION.",time:"48:00",objective:"Identifier les capacités humaines stratégiques.",script:"« Ce sont ces capacités que nous devons renforcer pendant que les machines deviennent meilleures sur d'autres tâches. »",interaction:"Demander laquelle doit être développée en priorité.",transition:"→ PARTIE IV"},
{headline:"PARTIE IV",subheadline:"QUI DOIT FAIRE<br><span class='accent'>QUOI ?</span>",time:"50:00",objective:"Transformer les idées en décisions concrètes.",script:"« Maintenant, on va arrêter de parler en théorie. Je vais vous donner des situations. Et vous allez devoir choisir. »",interaction:"Préparer la salle à répondre : Humain, IA ou Humain + IA.",transition:"→ RÈGLE DU JEU"},
{headline:"LE JEU EST SIMPLE.",subheadline:"POUR CHAQUE SITUATION :<br><span class='accent'>HUMAIN ?</span> · IA ? · ENSEMBLE ?",time:"51:00",objective:"Installer le mécanisme interactif.",script:"« Il n'y a pas de réponse magique. Ce qui compte, c'est votre raisonnement. »",interaction:"Faire répondre à main levée.",transition:"→ SITUATION 01"},
{headline:"SITUATION 01",subheadline:"UN CLIENT EN COLÈRE<br>ATTEND UNE RÉPONSE.",time:"52:00",objective:"Faire distinguer automatisation et responsabilité relationnelle.",script:"« Qui répond ? Un humain ? Une IA ? Ou un système hybride ? »",interaction:"Vote rapide, puis demander pourquoi.",transition:"→ MA RÉPONSE"},
{headline:"MA RÉPONSE ?",subheadline:"<span class='accent'>HUMAIN + IA.</span>",time:"54:00",objective:"Montrer une collaboration bien conçue.",script:"« L'IA peut analyser l'historique, préparer un brouillon et identifier les informations importantes. Mais un humain doit gérer le contexte, l'émotion et la relation. »",interaction:"Comparer avec les réponses du public.",transition:"→ SITUATION 02"},
{headline:"SITUATION 02",subheadline:"10 000 LIGNES DE DONNÉES<br>DOIVENT ÊTRE ANALYSÉES.",time:"56:00",objective:"Identifier une tâche fortement augmentable.",script:"« Même question. Qui doit faire quoi ? »",interaction:"Vote rapide.",transition:"→ LE PIÈGE"},
{headline:"LE PIÈGE,",subheadline:"CE N'EST PAS DE DIRE<br><span class='accent'>« IA PARTOUT ».</span>",time:"58:00",objective:"Éviter l'enthousiasme technologique naïf.",script:"« L'IA peut accélérer l'analyse. Mais quelqu'un doit vérifier les hypothèses, comprendre les anomalies et décider de ce qui compte réellement. »",interaction:"Demander : « Qu'est-ce qui pourrait mal tourner ? »",transition:"→ SITUATION 03"},
{headline:"SITUATION 03",subheadline:"UNE DÉCISION À FORT IMPACT<br>DOIT ÊTRE PRISE.",time:"60:00",objective:"Introduire la question du jugement et de la responsabilité.",script:"« Une IA propose une décision. Elle semble logique. Mais elle aura des conséquences importantes. Qui décide ? »",interaction:"Vote puis débat court.",transition:"→ LA DIFFÉRENCE"},
{headline:"UNE BONNE IA",subheadline:"PEUT PRODUIRE<br>UNE MAUVAISE DÉCISION.",time:"62:00",objective:"Faire comprendre la différence entre qualité de sortie et qualité de décision.",script:"« Une réponse cohérente n'est pas automatiquement une bonne décision. Une décision vit dans un contexte, avec des conséquences et des responsabilités. »",interaction:"Silence de quelques secondes.",transition:"→ LA QUESTION"},
{headline:"LA BONNE QUESTION",subheadline:"N'EST PAS :<br><span class='accent'>« QUE PEUT FAIRE L'IA ? »</span>",time:"64:00",objective:"Changer le cadre mental.",script:"« Cette question est trop limitée. »",interaction:"Laisser la phrase incomplète un instant.",transition:"→ LA VRAIE QUESTION"},
{headline:"LA VRAIE QUESTION",subheadline:"COMMENT ALLONS-NOUS<br><span class='accent'>RÉPARTIR LE TRAVAIL ?</span>",time:"65:00",objective:"Donner le principe opérationnel central.",script:"« Entre les humains, les logiciels, les IA et demain les agents autonomes : comment concevons-nous la répartition du travail ? »",interaction:"Faire reformuler l'idée par un participant.",transition:"→ PARTIE V"},
{headline:"PARTIE V",subheadline:"VOTRE AVANTAGE<br>N'EST PAS L'OUTIL.",time:"67:00",objective:"Préparer la conclusion stratégique.",script:"« Maintenant que nous avons compris le basculement, une dernière question devient essentielle : où se trouve votre avantage ? »",interaction:"Transition calme.",transition:"→ CE QUI SE PÉRIME"}
,
{headline:"CE QUI SE PÉRIME",subheadline:"LES OUTILS.<br>LES INTERFACES.<br>LES RECETTES.",time:"68:00",objective:"Montrer pourquoi courir après chaque outil est une mauvaise stratégie.",script:"« L'outil que vous maîtrisez aujourd'hui peut être remplacé demain. La vraie question est donc : sur quoi construire une compétence durable ? »",interaction:"Demander quels outils ont déjà disparu de leurs habitudes.",transition:"→ CE QUI RESTE"},
{headline:"CE QUI RESTE",subheadline:"COMPRENDRE LES <span class='accent'>PROBLÈMES.</span>",time:"70:00",objective:"Placer la compréhension des problèmes au sommet des compétences.",script:"« Une machine peut générer cent réponses. Mais elle ne décide pas seule quel problème mérite réellement d'être résolu. »",interaction:"Question : « Combien de fois avons-nous résolu le mauvais problème ? »",transition:"→ JUGER"},
{headline:"CE QUI RESTE",subheadline:"SAVOIR <span class='accent'>JUGER.</span>",time:"72:00",objective:"Faire comprendre la valeur du discernement.",script:"« Plus vous recevez de réponses rapidement, plus votre capacité à les évaluer devient importante. »",interaction:"Demander : « Comment savez-vous qu'une réponse est bonne ? »",transition:"→ CONCEVOIR"},
{headline:"CE QUI RESTE",subheadline:"SAVOIR <span class='accent'>CONCEVOIR.</span>",time:"74:00",objective:"Introduire la pensée systémique.",script:"« Concevoir, c'est décider comment les éléments vont fonctionner ensemble. Les personnes, les données, les outils et les règles. »",interaction:"Faire le lien avec les projets des participants.",transition:"→ COMMUNIQUER"},
{headline:"CE QUI RESTE",subheadline:"SAVOIR <span class='accent'>COMMUNIQUER.</span>",time:"76:00",objective:"Montrer que l'orchestration dépend de la communication.",script:"« Une intention mal formulée produit un système mal orienté, qu'elle soit donnée à un humain ou à une IA. »",interaction:"Faire remarquer que communiquer n'est pas seulement écrire un prompt.",transition:"→ APPRENDRE"},
{headline:"ET SURTOUT,",subheadline:"SAVOIR <span class='accent'>APPRENDRE.</span>",time:"78:00",objective:"Faire de l'apprentissage continu la compétence d'adaptation.",script:"« Le but n'est pas de mémoriser tous les outils. Le but est de devenir capable d'apprendre rapidement quand le paysage change. »",interaction:"Demander quelle compétence ils ont dû apprendre récemment.",transition:"→ LE NOUVEAU PROFIL"},
{headline:"LE NOUVEAU PROFIL",subheadline:"N'EST PAS CELUI QUI UTILISE<br>LE PLUS D'OUTILS.",time:"80:00",objective:"Casser la logique de collection d'outils.",script:"« Posséder cinquante outils ne crée pas automatiquement cinquante fois plus de valeur. »",interaction:"Pause.",transition:"→ C'EST CELUI"},
{headline:"C'EST CELUI QUI",subheadline:"SAIT QUAND UTILISER.<br>QUAND VÉRIFIER.<br>QUAND ARRÊTER.<br>ET QUAND DÉCIDER.",time:"82:00",objective:"Définir la maturité dans le travail augmenté.",script:"« La compétence n'est pas l'automatisation maximale. C'est la bonne décision sur le bon niveau d'automatisation. »",interaction:"Demander quel mot leur paraît le plus important.",transition:"→ VOTRE SYSTÈME"},
{headline:"CONSTRUISEZ VOTRE<br><span class='accent'>SYSTÈME PERSONNEL.</span>",subheadline:"PAS UNE COLLECTION D'OUTILS.",time:"84:00",objective:"Donner une direction pratique.",script:"« Identifiez vos problèmes récurrents. Vos tâches répétitives. Vos décisions difficiles. Puis concevez un système autour de votre réalité. »",interaction:"Inviter chacun à noter un problème récurrent.",transition:"→ EXERCICE"},
{headline:"EXERCICE : 5 MINUTES",subheadline:"CHOISISSEZ UN PROBLÈME<br>QUE VOUS RENCONTREZ CHAQUE SEMAINE.",time:"86:00",objective:"Faire passer de la réflexion à l'action.",script:"« Pas un problème imaginaire. Un problème réel, répétitif, qui vous coûte du temps ou de l'énergie. »",interaction:"5 minutes d'écriture individuelle.",transition:"→ CARTOGRAPHIEZ"},
{headline:"POSEZ-VOUS 4 QUESTIONS",subheadline:"1. QU'EST-CE QUI SE RÉPÈTE ?<br>2. QU'EST-CE QUI PEUT ÊTRE AUGMENTÉ ?<br>3. QU'EST-CE QUI DOIT RESTER HUMAIN ?<br>4. QUI EST RESPONSABLE ?",time:"91:00",objective:"Donner un cadre simple d'analyse.",script:"« Voici votre premier cadre d'architecture du travail augmenté. »",interaction:"Laisser les participants appliquer les quatre questions.",transition:"→ VOTRE PREMIER SYSTÈME"},
{headline:"VOUS VENEZ DE FAIRE",subheadline:"LE PREMIER PAS VERS<br><span class='accent'>VOTRE SYSTÈME INTELLIGENT.</span>",time:"94:00",objective:"Faire reconnaître l'apprentissage réalisé.",script:"« Vous n'avez pas besoin d'attendre une technologie parfaite. Vous pouvez commencer par un seul problème. »",interaction:"Demander deux volontaires pour partager leur problème.",transition:"→ LA DERNIÈRE QUESTION"},
{headline:"UNE DERNIÈRE QUESTION.",time:"96:00",objective:"Préparer la conclusion émotionnelle.",script:"« Depuis le début, nous avons parlé du travail qui change. Mais la question finale est plus personnelle. »",interaction:"Silence.",transition:"→ DANS 12 MOIS"},
{headline:"DANS 12 MOIS,",subheadline:"VOTRE TRAVAIL AURA ENCORE CHANGÉ.",time:"97:00",objective:"Projeter le public dans un futur proche.",script:"« Pas parce qu'un seul outil aura tout transformé. Mais parce que la manière dont les systèmes travaillent ensemble aura continué d'évoluer. »",interaction:"Demander d'imaginer leur quotidien dans un an.",transition:"→ LA QUESTION FINALE"},
{headline:"LA QUESTION N'EST PAS",subheadline:"SI LE TRAVAIL VA CHANGER.",time:"99:00",objective:"Créer la structure de la conclusion.",script:"« Cette partie de l'histoire est déjà en cours. »",interaction:"Pause.",transition:"→ LA VRAIE QUESTION"},
{headline:"LA VRAIE QUESTION,",subheadline:"C'EST : QUEL RÔLE<br>ALLEZ-VOUS <span class='accent'>CHOISIR</span> ?",time:"100:00",objective:"Ramener la responsabilité au participant.",script:"« Attendre que les changements arrivent ? Consommer les outils ? Ou apprendre à concevoir les systèmes qui créeront le prochain travail ? »",interaction:"Regarder la salle sans parler pendant quelques secondes.",transition:"→ LE TRAVAIL CHANGE"},
{headline:"LE TRAVAIL CHANGE.",subheadline:"VOUS AUSSI.",time:"102:00",objective:"Conclure avec une phrase mémorable.",script:"« La transformation ne consiste pas à devenir une machine. Elle consiste à devenir meilleur dans ce que vous choisissez de faire avec les machines. »",interaction:"Laisser la slide respirer.",transition:"→ COMMENCEZ"},
{headline:"COMMENCEZ PETIT.",subheadline:"UN PROBLÈME.<br>UN SYSTÈME.<br>UNE EXPÉRIENCE.",time:"103:00",objective:"Éviter la paralysie et encourager l'action.",script:"« Ne partez pas ce soir avec une liste de cinquante outils. Partez avec un problème réel à transformer. »",interaction:"Demander à chacun de conserver sa note.",transition:"→ MERCI"},
{headline:"MERCI.",subheadline:"HASHCODE<br><span class='accent'>LE TRAVAIL CHANGE.</span>",time:"105:00",objective:"Fermer la session.",script:"Remercier le public. Ouvrir ensuite les échanges ou annoncer la prochaine session.",interaction:"Questions et discussions.",transition:"FIN"}

];
let currentSlide=0,startTime=Date.now();
const presentation=document.getElementById("presentation"),progressBar=document.getElementById("progress-bar");
document.body.insertAdjacentHTML("beforeend",`<aside class="presenter-panel"><div class="presenter-top"><span class="presenter-label">HASHCODE</span><span class="presenter-private">PRIVÉ</span></div><h2>Vue présentateur</h2><div class="timer" id="timer">00:00</div><h3 id="slide-title"></h3><p><strong>Objectif</strong><br><span id="objective"></span></p><p><strong>Script</strong><br><span id="script"></span></p><p><strong>Interaction</strong><br><span id="interaction"></span></p><p><strong>Transition</strong><br><span id="transition"></span></p><div class="presenter-actions"><button class="presenter-prev">← Précédente</button><button class="presenter-next">Suivante →</button></div><p class="presenter-shortcuts">← → navigation · R chronomètre · fermer cette fenêtre pour revenir au mode public</p></aside>`);
function renderSlides(){const s=slides[currentSlide];presentation.innerHTML=slides.map((slide,index)=>`<section class="slide ${slide.background?"has-background":""} ${index===currentSlide?"active":""}" style="${slide.background?`--slide-bg:url(${slide.background})`:""}">${slide.brand?`<div class="brand">${slide.brand}</div>`:""}${slide.kicker?`<div class="kicker">${slide.kicker}</div>`:""}${slide.headline?`<h1 class="headline">${slide.headline}</h1>`:""}${slide.subheadline?`<div class="subheadline">${slide.subheadline}</div>`:""}</section>`).join("");progressBar.style.width=`${((currentSlide+1)/slides.length)*100}%`;document.getElementById("slide-title").textContent=`SLIDE ${currentSlide+1}/${slides.length} · cible ${s.time}`;document.getElementById("objective").textContent=s.objective;document.getElementById("script").textContent=s.script;document.getElementById("interaction").textContent=s.interaction;document.getElementById("transition").textContent=s.transition}
function nextSlide(){if(currentSlide<slides.length-1){currentSlide++;renderSlides()}}function previousSlide(){if(currentSlide>0){currentSlide--;renderSlides()}}
function openPresenter(){const url=new URL(window.location.href);url.searchParams.set("presenter","1");const w=window.open(url.toString(),"hashcode-presenter","popup=yes,width=900,height=900");if(!w){alert("Autorise les fenêtres contextuelles pour ouvrir la vue présentateur.")}}
const isPresenter=new URLSearchParams(window.location.search).get("presenter")==="1";
if(isPresenter){
document.body.classList.add("presenter-window");
document.getElementById("presentation").style.display="none";
document.getElementById("progress").style.display="none";
document.getElementById("controls-hint").textContent="Vue privée · synchronisée avec la présentation";
document.body.classList.add("presenter-mode");
}
function presenterNavigate(delta){
if(!isPresenter)return;
currentSlide=Math.max(0,Math.min(slides.length-1,currentSlide+delta));
renderSlides();
broadcast();
}
document.addEventListener("click",e=>{
if(!isPresenter)return;
const panel=document.querySelector(".presenter-panel");
if(e.target.closest(".presenter-next"))presenterNavigate(1);
if(e.target.closest(".presenter-prev"))presenterNavigate(-1);
});

function broadcast(){localStorage.setItem("hashcode-session-01-slide",JSON.stringify({index:currentSlide,ts:Date.now()}))}
function syncFromStorage(){const raw=localStorage.getItem("hashcode-session-01-slide");if(!raw)return;const data=JSON.parse(raw);if(data.index!==currentSlide){currentSlide=data.index;renderSlides()}}
window.addEventListener("storage",e=>{if(e.key==="hashcode-session-01-slide"&&isPresenter)syncFromStorage()});
const originalRender=renderSlides;renderSlides=function(){originalRender();if(!isPresenter)broadcast()};
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight"||e.key===" "){e.preventDefault();isPresenter?presenterNavigate(1):nextSlide()}if(e.key==="ArrowLeft"){isPresenter?presenterNavigate(-1):previousSlide()}if(e.key.toLowerCase()==="p"&&!isPresenter){openPresenter()}if(e.key.toLowerCase()==="f"&&!isPresenter){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}if(e.key.toLowerCase()==="r"){startTime=Date.now()}});
renderSlides();